#!/bin/bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
SDK_ROOT="${ANDROID_SDK_ROOT:-/usr/local/lib/android/sdk}"
BUILD_TOOLS="${SDK_ROOT}/build-tools/34.0.0"
ANDROID_JAR="${SDK_ROOT}/platforms/android-34/android.jar"
SRC_DIR="$REPO_DIR/app/src/main"
OUT_DIR="$REPO_DIR/.apkbuild"
APK_DIR="$REPO_DIR/apks"

mkdir -p "$OUT_DIR/compiled" "$OUT_DIR/gen" "$OUT_DIR/classes" "$APK_DIR"

# Compile each XML resource into the AAPT package file.
find "$SRC_DIR/res" -type f -name '*.xml' -print0 | while IFS= read -r -d '' file; do
  "$BUILD_TOOLS/aapt2" compile -o "$OUT_DIR/compiled" "$file"
done

# Add the manifest and link resources into an APK package.
"$BUILD_TOOLS/aapt2" link \
  -I "$ANDROID_JAR" \
  --manifest "$SRC_DIR/AndroidManifest.xml" \
  -R "$OUT_DIR/compiled" \
  --java "$OUT_DIR/gen" \
  -o "$OUT_DIR/resources.apk"

# Compile Java sources generated by AAPT and the app sources.
find "$OUT_DIR/gen" -name '*.java' -print > "$OUT_DIR/sources.txt"
find "$SRC_DIR/java" -name '*.java' -print >> "$OUT_DIR/sources.txt"

javac -classpath "$ANDROID_JAR" -d "$OUT_DIR/classes" @"$OUT_DIR/sources.txt"

# Convert compiled classes into a DEX file.
"$BUILD_TOOLS/d8" --lib "$ANDROID_JAR" --output "$OUT_DIR/classes.dex" $(find "$OUT_DIR/classes" -name '*.class' -print)

# Package resources + dex into an unsigned APK and align it.
zip -q -j "$OUT_DIR/unsigned.apk" "$OUT_DIR/resources.apk"
zip -q -g "$OUT_DIR/unsigned.apk" "$OUT_DIR/classes.dex"
"$BUILD_TOOLS/zipalign" -p -f 4 "$OUT_DIR/unsigned.apk" "$OUT_DIR/aligned.apk"

# Sign it with a debug keystore.
keytool -genkeypair -v -keystore "$OUT_DIR/debug.keystore" -alias androiddebugkey \
  -keyalg RSA -keysize 2048 -validity 10000 \
  -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US" >/dev/null 2>&1

"$BUILD_TOOLS/apksigner" sign --ks "$OUT_DIR/debug.keystore" --ks-pass pass:android --key-pass pass:android --out "$APK_DIR/android-cloud-emulator.apk" "$OUT_DIR/aligned.apk"

ls -l "$APK_DIR/android-cloud-emulator.apk"
